services:

  app:
    image: qasim00programmer/solution-api:1.0.0

    container_name: solution_app

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - solution_network


  nginx:
    image: qasim00programmer/solution-nginx:1.0.0

    container_name: solution_nginx

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - app

    networks:
      - solution_network


  mysql:
    image: mysql:8.0

    container_name: solution_mysql

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - solution_network


volumes:
  mysql_data:


networks:
  solution_network:
